### GET hello
GET http://localhost:8888/hello

### GET gw
GET http://localhost:8888/ga


### POST user
POST http://localhost:8888/ga/com.stephenshen.ssrpc.demo.api.UserService
Content-Type: application/json

{
  "service": "com.stephenshen.ssrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}